name=PTSolns_I2Connect_AHT20
version=1.0.0
author=PTSolns
maintainer=PTSolns
sentence=Arduino library for the PTSolns I2Connect AHT20 module.
paragraph=Provides simple read humidity and temperature for the PTSolns I2Connect AHT20 module using I2C.
category=Data Storage
url=https://github.com/PTSolns/I2Connect_AHT20
architectures=*
includes=PTSolns_I2Connect_AHT20.h
